baseURL = "https://ks3import.github.io"
languageCode = "en-us"
title = "KS3-Import"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
  description = "数据迁移工具"
  author = "ks3"
